/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 14.1 		*/
/*  Created On : 22-Mar-2025 14:06:13 				*/
/*  DBMS       : MSAccess 						*/
/* ---------------------------------------------------- */

/* Drop Foreign Key Constraints */

ALTER TABLE [Administrator] DROP CONSTRAINT [FK_Administrator_Osoba]

ALTER TABLE [GeneratorRaportówSprzeda¿owych] DROP CONSTRAINT [FK_Generator raportów sprzeda¿owych_Korzysta]

ALTER TABLE [Klient] DROP CONSTRAINT [FK_Klient_Wype³nia]

ALTER TABLE [Klient] DROP CONSTRAINT [FK_Klient_Osoba]

ALTER TABLE [Menad¿er] DROP CONSTRAINT [FK_Menad¿er_Osoba]

ALTER TABLE [PanelZarz¹dzaniaKontem] DROP CONSTRAINT [FK_Panel zarz¹dzania kontem_Obs³uguje]

ALTER TABLE [Pracownik] DROP CONSTRAINT [FK_Pracownik_Osoba]

ALTER TABLE [Produkt] DROP CONSTRAINT [FK_Produkt_Zarz¹dza]

ALTER TABLE [Produkt] DROP CONSTRAINT [FK_Produkt_Przegl¹da]

ALTER TABLE [U¿ytkownik] DROP CONSTRAINT [FK_U¿ytkownik_Klient]

ALTER TABLE [Zamówienie] DROP CONSTRAINT [FK_Zamówienie_Administruje]

ALTER TABLE [Zamówienie] DROP CONSTRAINT [FK_Zamówienie_Realizuje]

ALTER TABLE [Zamówienie] DROP CONSTRAINT [FK_Zamówienie_Tworzy]

/* Drop Tables */

DROP TABLE [Administrator]

DROP TABLE [FolmularzRejestracyjny]

DROP TABLE [GeneratorRaportówSprzeda¿owych]

DROP TABLE [Klient]

DROP TABLE [Menad¿er]

DROP TABLE [Osoba]

DROP TABLE [PanelZarz¹dzaniaKontem]

DROP TABLE [Pracownik]

DROP TABLE [Produkt]

DROP TABLE [U¿ytkownik]

DROP TABLE [Zamówienie]

/* Create Tables */

CREATE TABLE [Administrator]
(
	[Has³o] Text(50) NULL,
	[Login] Text(50) NULL,
	[AdministratorID] Short NOT NULL
)

CREATE TABLE [FolmularzRejestracyjny]
(
	[Adres] Text(50) NULL,
	[Email] Text(50) NULL,
	[Has³o] Text(50) NULL,
	[NazwaU¿ytkownika] Text(50) NULL,
	[PotwierdzenieHas³a] Text(50) NULL,
	[ZgodaNaRegulaminSystemu] YesNo NULL,
	[FolmularzRejestracyjnyID] Short NOT NULL
)

CREATE TABLE [GeneratorRaportówSprzeda¿owych]
(
	[DataKoñcowa] DateTime NULL,
	[DataPocz¹tkowa] DateTime NULL,
	[GeneratorRaportówSprzeda¿owychID] Short NOT NULL,
	[Menad¿erID] Short NOT NULL
)

CREATE TABLE [Klient]
(
	[KlientID] Short NOT NULL,
	[FolmularzRejestracyjnyID] Short NOT NULL
)

CREATE TABLE [Menad¿er]
(
	[Has³o] Text(50) NULL,
	[Login] Text(50) NULL,
	[Menad¿erID] Short NOT NULL
)

CREATE TABLE [Osoba]
(
	[Id] Short NULL,
	[Imiê] Text(50) NULL,
	[Nazwisko] Text(50) NULL,
	[OsobaID] Short NOT NULL
)

CREATE TABLE [PanelZarz¹dzaniaKontem]
(
	[KodRabatowy] Text(50) NULL,
	[ZamówieniaU¿ytkownika] Text(50) NULL,
	[PanelZarz¹dzaniaKontemID] Short NOT NULL,
	[U¿ytkownikID] Short NOT NULL
)

CREATE TABLE [Pracownik]
(
	[Has³o] Text(50) NULL,
	[Login] Text(50) NULL,
	[Stanowisko] Text(50) NULL,
	[PracownikID] Short NOT NULL
)

CREATE TABLE [Produkt]
(
	[Cena] Double NULL,
	[Id] Short NULL,
	[IloœæWMagazynie] Short NULL,
	[Nazwa] Text(50) NULL,
	[Opis] Text(50) NULL,
	[ProduktID] Short NOT NULL,
	[AdministratorID] Short NOT NULL,
	[U¿ytkownikID] Short NOT NULL
)

CREATE TABLE [U¿ytkownik]
(
	[Has³o] Text(50) NULL,
	[Login] Text(50) NULL,
	[U¿ytkownikID] Short NOT NULL
)

CREATE TABLE [Zamówienie]
(
	[AdresDostawy] Text(50) NULL,
	[Ca³kowitaWartoœæ] Double NULL,
	[ListaProduktów] Text(50) NULL,
	[Notatka] Text(50) NULL,
	[SposóbDostawy] Text(50) NULL,
	[ZamówienieID] Short NOT NULL,
	[AdministratorID] Short NOT NULL,
	[PracownikID] Short NOT NULL,
	[U¿ytkownikID] Short NOT NULL
)

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [Administrator] ADD CONSTRAINT [PK_Administrator]
	PRIMARY KEY ([AdministratorID])

ALTER TABLE [FolmularzRejestracyjny] ADD CONSTRAINT [PK_FolmularzRejestracyjny]
	PRIMARY KEY ([FolmularzRejestracyjnyID])

ALTER TABLE [GeneratorRaportówSprzeda¿owych] ADD CONSTRAINT [PK_GeneratorRaportówSprzeda¿owych]
	PRIMARY KEY ([GeneratorRaportówSprzeda¿owychID])

ALTER TABLE [Klient] ADD CONSTRAINT [PK_Klient]
	PRIMARY KEY ([KlientID])

ALTER TABLE [Menad¿er] ADD CONSTRAINT [PK_Menad¿er]
	PRIMARY KEY ([Menad¿erID])

ALTER TABLE [Osoba] ADD CONSTRAINT [PK_Osoba]
	PRIMARY KEY ([OsobaID])

ALTER TABLE [PanelZarz¹dzaniaKontem] ADD CONSTRAINT [PK_PanelZarz¹dzaniaKontem]
	PRIMARY KEY ([PanelZarz¹dzaniaKontemID])

ALTER TABLE [Pracownik] ADD CONSTRAINT [PK_Pracownik]
	PRIMARY KEY ([PracownikID])

ALTER TABLE [Produkt] ADD CONSTRAINT [PK_Produkt]
	PRIMARY KEY ([ProduktID])

ALTER TABLE [U¿ytkownik] ADD CONSTRAINT [PK_U¿ytkownik]
	PRIMARY KEY ([U¿ytkownikID])

ALTER TABLE [Zamówienie] ADD CONSTRAINT [PK_Zamówienie]
	PRIMARY KEY ([ZamówienieID])

/* Create Foreign Key Constraints */

ALTER TABLE [Administrator] ADD CONSTRAINT [FK_Administrator_Osoba]
	FOREIGN KEY ([AdministratorID]) REFERENCES [Osoba] ([OsobaID])

ALTER TABLE [GeneratorRaportówSprzeda¿owych] ADD CONSTRAINT [FK_Generator raportów sprzeda¿owych_Korzysta]
	FOREIGN KEY ([Menad¿erID]) REFERENCES [Menad¿er] ([Menad¿erID])

ALTER TABLE [Klient] ADD CONSTRAINT [FK_Klient_Wype³nia]
	FOREIGN KEY ([FolmularzRejestracyjnyID]) REFERENCES [FolmularzRejestracyjny] ([FolmularzRejestracyjnyID])

ALTER TABLE [Klient] ADD CONSTRAINT [FK_Klient_Osoba]
	FOREIGN KEY ([KlientID]) REFERENCES [Osoba] ([OsobaID])

ALTER TABLE [Menad¿er] ADD CONSTRAINT [FK_Menad¿er_Osoba]
	FOREIGN KEY ([Menad¿erID]) REFERENCES [Osoba] ([OsobaID])

ALTER TABLE [PanelZarz¹dzaniaKontem] ADD CONSTRAINT [FK_Panel zarz¹dzania kontem_Obs³uguje]
	FOREIGN KEY ([U¿ytkownikID]) REFERENCES [U¿ytkownik] ([U¿ytkownikID])

ALTER TABLE [Pracownik] ADD CONSTRAINT [FK_Pracownik_Osoba]
	FOREIGN KEY ([PracownikID]) REFERENCES [Osoba] ([OsobaID])

ALTER TABLE [Produkt] ADD CONSTRAINT [FK_Produkt_Zarz¹dza]
	FOREIGN KEY ([AdministratorID]) REFERENCES [Administrator] ([AdministratorID])

ALTER TABLE [Produkt] ADD CONSTRAINT [FK_Produkt_Przegl¹da]
	FOREIGN KEY ([U¿ytkownikID]) REFERENCES [U¿ytkownik] ([U¿ytkownikID])

ALTER TABLE [U¿ytkownik] ADD CONSTRAINT [FK_U¿ytkownik_Klient]
	FOREIGN KEY ([U¿ytkownikID]) REFERENCES [Klient] ([KlientID])

ALTER TABLE [Zamówienie] ADD CONSTRAINT [FK_Zamówienie_Administruje]
	FOREIGN KEY ([AdministratorID]) REFERENCES [Administrator] ([AdministratorID])

ALTER TABLE [Zamówienie] ADD CONSTRAINT [FK_Zamówienie_Realizuje]
	FOREIGN KEY ([PracownikID]) REFERENCES [Pracownik] ([PracownikID])

ALTER TABLE [Zamówienie] ADD CONSTRAINT [FK_Zamówienie_Tworzy]
	FOREIGN KEY ([U¿ytkownikID]) REFERENCES [U¿ytkownik] ([U¿ytkownikID])
